db:
  image: mongo:3.1
  ports:
    - "27017:27017"

web:
  build: .
  command: /usr/local/bundle/bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - "9292:9292"
  links:
    - db
  volumes:
    - .:/sequoia-app
